### Data Ingestion and Data Cleaning

In [3]:
# importing pandas and os library
import pandas as pd
import os

In [ ]:
# loading the dataset to df: DataFrame
df = pd.read_csv(r'C:\Users\as330\OneDrive\Desktop\UAC-Care-System\data\raw\HHS_Unaccompanied_Alien_Children_Program.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'UAC-Care-System\\data\\raw\\HHS_Unaccompanied_Alien_Children_Program.csv'

In [5]:
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [6]:
df.shape

(1170, 6)

In [7]:
df.isnull().sum()

Date                                               450
Children apprehended and placed in CBP custody*    450
Children in CBP custody                            450
Children transferred out of CBP custody            450
Children in HHS Care                               450
Children discharged from HHS Care                  450
dtype: int64

In [8]:
df[df.isnull().any(axis=1)]

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
720,NaN,NaN,NaN,NaN,NaN,NaN
721,NaN,NaN,NaN,NaN,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df = df.dropna()

In [10]:
df.shape

(720, 6)

In [11]:
df.isnull().sum()

Date                                               0
Children apprehended and placed in CBP custody*    0
Children in CBP custody                            0
Children transferred out of CBP custody            0
Children in HHS Care                               0
Children discharged from HHS Care                  0
dtype: int64

In [12]:
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [13]:
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2025-12-21,6.0,18.0,11.0,"2,484",14.0
1,2025-12-18,11.0,50.0,6.0,"2,472",16.0
2,2025-12-17,7.0,31.0,11.0,"2,481",10.0
3,2025-12-16,8.0,54.0,15.0,"2,468",9.0
4,2025-12-15,11.0,42.0,9.0,"2,470",7.0

In [14]:
df =  df.sort_values(by="Date")

In [15]:
df.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
719,2023-01-12,33.0,53.0,34.0,"6,566",436.0
718,2023-01-22,32.0,49.0,39.0,"7,122",227.0
717,2023-01-23,32.0,50.0,39.0,"7,280",181.0
716,2023-01-24,47.0,42.0,47.0,"7,433",175.0
715,2023-01-25,20.0,22.0,41.0,"7,538",180.0

In [ ]:
df = df.set_index("Date")

In [23]:
daily_index = pd.date_range(
    start=df.index.min(),
    end=df.index.max(),
    freq="D"
)

In [24]:
df = df.reindex(daily_index)

In [33]:
cols = ["Children in HHS Care"]

for col in cols:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace(",", "", regex=False),
        errors="coerce"
    )

In [34]:
df.shape

(1075, 5)

In [35]:
import os

folder_path = r'UAC-Care-System\data\cleaned_data'

print("Path:", folder_path)
print("Parent exists:", os.path.exists(os.path.dirname(folder_path)))

os.makedirs(folder_path, exist_ok=True)

print("Folder exists:", os.path.exists(folder_path))

Path: UAC-Care-System\data\cleaned_data
Parent exists: False
Folder exists: True

In [36]:
df.to_csv(os.path.join(folder_path, 'cleaned_data.csv'), index=True)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1075 entries, 2023-01-12 to 2025-12-21
Freq: D
Data columns (total 5 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Children apprehended and placed in CBP custody*  720 non-null    float64
 1   Children in CBP custody                          720 non-null    float64
 2   Children transferred out of CBP custody          720 non-null    float64
 3   Children in HHS Care                             720 non-null    float64
 4   Children discharged from HHS Care                720 non-null    float64
dtypes: float64(5)
memory usage: 50.4 KB

In [38]:
df.head()

,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
2023-01-12,33.0,53.0,34.0,6566.0,436.0
2023-01-13,NaN,NaN,NaN,NaN,NaN
2023-01-14,NaN,NaN,NaN,NaN,NaN
2023-01-15,NaN,NaN,NaN,NaN,NaN
2023-01-16,NaN,NaN,NaN,NaN,NaN