In [4]:
import pandas as pd
import os

In [5]:
data = pd.read_csv(r'C:\Users\as330\OneDrive\Desktop\uac-capacity-analytics\data\raw\HHS_Unaccompanied_Alien_Children_Program.csv')

In [6]:
data.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,"December 21, 2025",6.0,18.0,11.0,"2,484",14.0
1,"December 18, 2025",11.0,50.0,6.0,"2,472",16.0
2,"December 17, 2025",7.0,31.0,11.0,"2,481",10.0
3,"December 16, 2025",8.0,54.0,15.0,"2,468",9.0
4,"December 15, 2025",11.0,42.0,9.0,"2,470",7.0

In [7]:
data.shape

(1170, 6)

In [8]:
data.isnull().sum()

Date                                               450
Children apprehended and placed in CBP custody*    450
Children in CBP custody                            450
Children transferred out of CBP custody            450
Children in HHS Care                               450
Children discharged from HHS Care                  450
dtype: int64

In [9]:
data[data.isnull().any(axis=1)]

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
720,NaN,NaN,NaN,NaN,NaN,NaN
721,NaN,NaN,NaN,NaN,NaN,NaN
722,NaN,NaN,NaN,NaN,NaN,NaN
723,NaN,NaN,NaN,NaN,NaN,NaN
724,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1165,NaN,NaN,NaN,NaN,NaN,NaN
1166,NaN,NaN,NaN,NaN,NaN,NaN
1167,NaN,NaN,NaN,NaN,NaN,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN
1169,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
data = data.dropna()

In [11]:
data.shape

(720, 6)

In [12]:
data.isnull().sum()

Date                                               0
Children apprehended and placed in CBP custody*    0
Children in CBP custody                            0
Children transferred out of CBP custody            0
Children in HHS Care                               0
Children discharged from HHS Care                  0
dtype: int64

In [13]:
data["Date"] = pd.to_datetime(data["Date"], errors="coerce")

In [14]:
data.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
0,2025-12-21,6.0,18.0,11.0,"2,484",14.0
1,2025-12-18,11.0,50.0,6.0,"2,472",16.0
2,2025-12-17,7.0,31.0,11.0,"2,481",10.0
3,2025-12-16,8.0,54.0,15.0,"2,468",9.0
4,2025-12-15,11.0,42.0,9.0,"2,470",7.0

In [15]:
data =  data.sort_values(by="Date")

In [16]:
data.head()

,Date,Children apprehended and placed in CBP custody*,Children in CBP custody,Children transferred out of CBP custody,Children in HHS Care,Children discharged from HHS Care
719,2023-01-12,33.0,53.0,34.0,"6,566",436.0
718,2023-01-22,32.0,49.0,39.0,"7,122",227.0
717,2023-01-23,32.0,50.0,39.0,"7,280",181.0
716,2023-01-24,47.0,42.0,47.0,"7,433",175.0
715,2023-01-25,20.0,22.0,41.0,"7,538",180.0

In [17]:
data = data.set_index("Date")

In [18]:
daily_index = pd.date_range(
    start=data.index.min(),
    end=data.index.max(),
    freq="D"
)

In [19]:
data = data.reindex(daily_index)

In [20]:
data.shape

(1075, 5)

In [21]:
folder_path = r'C:\Users\as330\OneDrive\Desktop\uac-capacity-analytics\data\cleaned_data'
os.makedirs(folder_path, exist_ok=True)

In [24]:
data.to_csv(os.path.join(folder_path, 'cleaned_data.csv'), index=True)